config/routes.rb
TravelSage::Application.routes.draw do
  match 'auth/facebook/callback', to: 'sessions#create_with_facebook', via: :get
  match 'auth/twitter/callback', to: 'sessions#create_with_twitter', via: :get
  match 'auth/failure', to: redirect('/'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get

  root :to => 'main#index'
  resources :articles
  resources :comments
  resources :users
  resources :cities
  resources :tags
  resources :categories
  resources :votes, only: [:create, :update, :destroy]
  match '/filter', to: 'main#filter', via: [:post]
  match '/citysage', to: 'citysage#show', via: :get
  match '/about', to: 'about#show', via: :get
  match '/meetsages', to: 'meet#show', via: :get
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :tags
  has_many :categories, through: :tags
  has_many :itineraries
  has_many :cities, through: :itineraries
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
  belongs_to :user

  def self.filter(hash)
    # need to make case insensitive
    hash.delete_if {|k,v| v == ""}
    hash[:writer_type] = (hash[:writer_type]) if hash[:writer_type] != nil
    sql_base = "select distinct articles.* from articles
       left outer join tags
       on tags.article_id = articles.id
       left outer join categories
       on tags.category_id = categories.id
       left outer join itineraries
       on itineraries.article_id = articles.id
       left outer join cities
       on itineraries.city_id = cities.id
       join users
       on users.id = articles.user_id"

    condition_array = []
    key_array = []
    hash.each_key {|key| key_array << key}
    key_array.each_with_index do |key, i|
      operator = "and"
      operator = "where" if i == 0
      case key
      when :writer
        sql_base << "\n#{operator} users.username like ?"
        condition_array << hash[:writer]
      when :writer_type
         sql_base << "\n#{operator} users.status in (?)"
        condition_array << hash[:writer_type]
      when :city
        sql_base << "\n#{operator} cities.name like ?"
        condition_array << hash[:city]
      when :category
        sql_base << "\n#{operator} categories.name like ?"
        condition_array << hash[:category]
      end
    end
    sql_array = [sql_base,condition_array].flatten
    articles = Article.find_by_sql(sql_array)
    articles
  end







end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tags
  has_many :articles, through: :tags
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :itineraries
  has_many :articles, through: :itineraries
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  
  def self.find_with_omniauth(auth)
    Identity.find_by_provider_and_uid(auth['provider'], auth['uid'])
  end

  def self.create_with_omniauth(auth)
    Identity.create(uid: auth['uid'], provider: auth['provider'])
  end

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  belongs_to :city
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :category
  belongs_to :article

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :identities
  has_many :comments
  has_many :votes
  def self.create_with_omniauth(info)
    User.create(name: info['name'])
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voteable, polymorphic: true
  belongs_to :user
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @comment = Comment.new
    @article = Article.find(params["id"])
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params["id"])
    @articles = @city.articles
  end
end

app/controllers/citysage_controller.rb
class CitysageController < ApplicationController
  def show
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

    article = Article.find(params['article']['id'])
    # fix user_id
    @comment = Comment.create(text: params['comment']['text'], user_id: 11, commentable_type: "Article", commentable_id: article.id)
    # comment.user_id = current_user.id
    render :partial => 'comment'

    # redirect_to article_path(14)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @cities = City.all
    @categories = Category.all
  end
  def filter
    filter_hash = {city: params["city"], writer: params["writer"], category: params['category'], writer_type: params["writer_type"]}
    @articles = Article.filter(filter_hash)
    render "results", layout: true
  end
end

app/controllers/meet_controller.rb
class MeetController < ApplicationController
  def show
   
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_filter :verify_authenticity_token, only: :create
  def create_with_facebook
    auth = request.env['omniauth.auth']
    @identity = Identity.find_with_omniauth(auth)
    @identity = Identity.create_with_omniauth(auth) if @identity.nil?
    if @identity.user == current_user && current_user != (false || nil)
      redirect_to root_url 
    end
         
    if current_user && current_user != @identity.user
      @user = current_user
      @user.update(name: auth['extra']['raw_info']['name'])
      @identity.user = @user
      @identity.save
      @user.save
      redirect_to root_url, notice: "Successfully linked that account!"
    end

    if @identity.user && !current_user
      @user = @identity.user
      @user.update(name: auth['extra']['raw_info']['name'])
      @user.save
      session[:user_id] = @identity.user.id
      redirect_to user_path(@user.id)
    end


    if !current_user && @identity.user == nil
      @user = User.create(name: auth['extra']['raw_info']['name'])
      @identity.user = @user
      @identity.save!
      session[:user_id] = @identity.user.id
      
      redirect_to user_path(@user.id)
    end
  end

  def create_with_twitter
    auth = request.env['omniauth.auth']
    p ">>>>>>>>>>>>>"
    p auth
    @identity = Identity.find_with_omniauth(auth)
    @identity = Identity.create_with_omniauth(auth) if @identity.nil?
    if @identity.user == current_user && current_user != (false || nil)
      redirect_to root_url 
    end
    if current_user && current_user != @identity.user
      @user = current_user
      p "???????????????"
      p auth['extra']['raw_info']['screen_name']
      @user.update(handle: auth['extra']['raw_info']['screen_name'])
      @identity.user = @user
      @identity.save
      @user.save
      redirect_to root_url, notice: "Successfully linked that account!"
    end

    if @identity.user && !current_user
       p "???????????????"
      p auth['extra']['raw_info']['screen_name']
      @user = @identity.user
      @user.update(handle: auth['extra']['raw_info']['screen_name'])
      @user.save
      session[:user_id] = @identity.user.id
      redirect_to user_path(@user.id)
    end

    if !current_user && @identity.user == nil
      @user = User.create(handle: auth['extra']['raw_info']['screen_name'])
      @identity.user = @user
      @identity.save!
      session[:user_id] = @identity.user.id
      
      redirect_to user_path(@user.id)
    end
  end

  def destroy
    session[:user_id] = nil
  redirect_to root_url, notice: "Signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params["id"])
    @articles = @user.articles
    @profile = true if current_user == @user
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @user = User.find(10)
    @vote = Vote.where(voteable_id: params['voteable_id'], voteable_type: params['voteable_type'], user_id: 10).first_or_create
    @vote.update_attributes(value: params["value"])
    @voteable_type = params["voteable_type"]
    @voteable_id = params["voteable_id"]
    if @voteable_type == 'Article'
      @count = Article.find(params['voteable_id']).votes.sum(:value)
    elsif @voteable_type == 'Comment'
      @count = Comment.find(params['voteable_id']).votes.sum(:value)
    end
    @vote.save

  end

  def update
    p "Update"
    p params
  end

  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/about/show.html.erb
ABOUT US MOTHATRUCKER

app/views/citysage/show.html.erb
MY CITYSAGE PAGE

app/views/main/_articles.html.erb
<div class='articlesDiv'>
  <% @cities.each do |city|%>
  <%= link_to city_path(city), class: "cityLink"  do %>
    <%= city.name %>, <%= city.province %>
    <% end %>
      <%city.articles.each do |article|  %>
        <div class='singleArticle'>
          <div class='articleText'>
          <%= article.votes.sum(:value) %>
            <%= link_to 'Up', votes_path(value: 1, voteable_type: 'Article', voteable_id: article.id), method: "post", remote: true %>
            <%= link_to 'Down', votes_path(value: -1, voteable_type: 'Article', voteable_id: article.id), method: "post", remote: true %>
            <span class='articleTitle'><%=link_to article.title, article_path(article)%></span><br>
            <span class='articleAuthor'>By: <%=link_to article.user.username, user_path(article.user) %></span>
          </div>
          <span class='articleTags'>
            <% article.categories.each do |tag| %>
              <%= link_to tag.name, category_path(tag) %>|
            <% end %>
          </span>
        </div>
      <% end %>
  <% end %>
</div>

app/views/main/_filter.html.erb
 <%= form_tag('/filter', method: "post", class: ["filterForm", "hidden"]) do %>
  <%= label_tag(:city, "Filter by City:") %>
  <%= text_field_tag(:city) %>
  <%= label_tag(:writer, "Filter by Writer Name:") %>
  <%= text_field_tag(:writer) %>
  <%= label_tag(:category, "Filter by Category:") %>
  <%= text_field_tag(:category) %>
  <%= label_tag(:writer_type, "Filter by Writer Type:") %>
  <%= select_tag(:writer_type, options_for_select([[nil],["Sage",0],["Traveler",1]])) %>
  <%= submit_tag("Update") %>
<% end %>

app/views/main/index.html.erb
<div class='intro'>
<span class='welcome'>Welcome to <span class='welcomeTravel'>Travel</span><span class='welcomeSage'>Sage</span> –</span> A guide that allows adventurous people to draw the curtain to the most exciting cities in the world.  As insanely-passionate travelers, we're here to help you customize your 

authentic experience.
<br>
<span class='callToAction'>Have an authentic experience to share?</span>  Click <%= link_to "here", "#", class: "submitContent" %> to upload your tale as one of our Travelers.
</div>

<div class='filterDiv'>To start, choose a feature article below – or – click <%=link_to "here", "#", class: "filterButton"%> to filter based upon your preferences:</div>
<%= render 'filter' %>
<%= render 'articles' %>

app/views/main/results.html.erb
<div class='cityLink'>Results</div>
<% @articles.each do |article| %>
  <div class='singleArticle'>
    <div class='articleText'>
      <span class='articleTitle'><%=link_to article.title, article_path(article)%></span><br>
      <span class='articleAuthor'>By: <%=link_to article.user.username, user_path(article.user) %></span>
    </div>
    <span class='articleTags'>
      <% article.categories.each do |tag| %>
        <%= link_to tag.name, category_path(tag) %>|
      <% end %>
    </span>
  </div>
<% end %>

app/views/meet/show.html.erb
MEET SOME BITCHES