config/routes.rb
TravelSage::Application.routes.draw do
  match 'auth/facebook/callback', to: 'sessions#create_with_facebook', via: :get
  match 'auth/twitter/callback', to: 'sessions#create_with_twitter', via: :get
  match 'auth/failure', to: redirect('/'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get

  root :to => 'main#index'
  resources :articles
  resources :comments
  resources :users
  resources :cities
  resources :tags
  resources :categories
  resources :votes, only: [:create, :update, :destroy]
  match '/filter', to: 'main#filter', via: [:post]
  match '/citysage', to: 'citysage#show', via: :get
  match '/about', to: 'about#show', via: :get
  match '/meetsages', to: 'meet#show', via: :get
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :identities
  has_many :comments
  has_many :votes
  def self.create_with_omniauth(info)
    User.create(name: info['name'])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params["id"])
    @articles = @user.articles
    @profile = true if current_user == @user
  end

end

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= @user.name %>
<%= @user.handle %>
<%= @user.id %>
<% if @profile %>
  <%= link_to "Sign in with Facebook", "/auth/facebook", class: "sign_in" %>
  <%= link_to "Sign in with Twitter", "/auth/twitter", class: "sign_in" %>
<% end %>
<% @articles.each do |article| %>
  <%= link_to article.title, article_path(article) %><br>
<% end %>